### PR TITLE
inital typescript version 

### PR DESCRIPTION
**Pull request by itschip**
You may want to merge this into a new branch, idk.

### CODE REVIEW

**Comment by itschip** [comment]
Let me know if you'd like to have a webpack created as well.

**Comment by itsxScrubz** [comment]
Yeah I just added it to a new branch. I'll update the post on cfx and add a readme to reflect this and give credit! Thanks for the pr!!

**Comment by itsxScrubz** [comment]
And I'm still sorta new to React, but I'm using rewire instead of doing webpack stuff. I'm not 100% what the benefits doing webpack vs rewire are.

**Comment by itschip** [comment]
> And I'm still sorta new to React, but I'm using rewire instead of doing webpack stuff. I'm not 100% sure what the benefits doing webpack vs rewire are.

Never tried 'rewire'. I use webpack as that is the common goto, and most people understand it.

After reading about 'rewire' (assuming I am reading about the one you are referring to), I don't quite see why you would use it for this 🤷‍♂️

**Pull request closed without merging**
